/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectogestion_calificaciones;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matgr
 */
public class FrmActas extends javax.swing.JFrame {

    /**
     * Creates new form FrmActas
     */
    DefaultTableModel modelo = new DefaultTableModel();
    int borrar;

    public FrmActas() {

        initComponents();
        jtProductos.setModel(modelo);
        try {

            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion conn = new Conexion();
            java.sql.Connection con = conn.getConexion();

            String sql = "SELECT  Nombre FROM grupos";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            while (rs.next()) {

                for (int i = 0; i < cantidadColumnas; i++) {
                    cbogrupo.addItem("" + rs.getObject(i + 1));
                }

            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }
        modelo.addColumn("Id");
        modelo.addColumn("Nombre");
        modelo.addColumn("Asignatura");
        int[] anchos = {50, 70, 110};
        for (int j = 0; j < jtProductos.getColumnCount(); j++) {
            jtProductos.getColumnModel().getColumn(j).setPreferredWidth(anchos[j]);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LBLusuarios = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbogrupo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProductos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JLabel();
        txtid = new javax.swing.JLabel();
        txtasignatura = new javax.swing.JLabel();
        JBTguardar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        LBLusuarios.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        LBLusuarios.setText("            Acta");

        jLabel1.setText("Seleccione el grupo:");

        cbogrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione" }));
        cbogrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbogrupoActionPerformed(evt);
            }
        });

        jtProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Asignatura"
            }
        ));
        jtProductos.setToolTipText("");
        jtProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtProductos);

        jLabel2.setText("Id:");

        jLabel3.setText("Asignatura:");

        jLabel4.setText("Nombre:");

        txtnombre.setText("...");

        txtid.setText("...");

        txtasignatura.setText("...");

        JBTguardar.setText("Añadir");
        JBTguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTguardarActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        jLabel5.setText("Alumnos matriculados:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(cbogrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(LBLusuarios)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtasignatura, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(JBTguardar)
                                .addGap(67, 67, 67)
                                .addComponent(eliminar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBLusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbogrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtasignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBTguardar)
                            .addComponent(eliminar))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtProductosMouseClicked
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            Conexion objCon = new Conexion();
            Connection conn = objCon.getConexion();

            int Fila = jtProductos.getSelectedRow();
            String codigo = jtProductos.getValueAt(Fila, 0).toString();
            String materia = jtProductos.getValueAt(Fila, 2).toString();
            ps = conn.prepareStatement("SELECT * FROM matricula WHERE Nif=? AND Asignatura=?");
            ps.setString(1, codigo);
            ps.setString(2, materia);
            rs = ps.executeQuery();

            while (rs.next()) {
                txtid.setText(rs.getString("Nif"));
                txtnombre.setText(rs.getString("Nombre_alu"));
                txtasignatura.setText(rs.getString("Asignatura"));

            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_jtProductosMouseClicked

    private void JBTguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTguardarActionPerformed
        PreparedStatement ps = null;
        int a = buscar();
        try {
            String comp = txtid.getText();
            System.out.println(comp);
            //int conv = Integer.parseInt(lblcupos1.getText());
            //int Fila = tablausuarios.getSelectedRow();
            String comp1 = "...";
            // String comp2 = "...";
            System.out.println(comp);
            if ("".equals(comp)) {
                comp = ".";
            }

            if ((comp1.equals(txtid.getText()))) {
                JOptionPane.showMessageDialog(null, "Porfavor llene todos los campos");
            } else {
                if (a == 1) {
                    JOptionPane.showMessageDialog(null, "El alumno ya se encuentra registrado en el acta");
                    limpiar();
                } else {
                    // num = Integer.parseInt(txtcedula.getText());

                    try {
                        Conexion objCon = new Conexion();
                        Connection conn = objCon.getConexion();
                        Acta p = new Acta();
                        ps = conn.prepareStatement("INSERT INTO acta (Nif,Nombre,Asignatura,Nota1,Nota2,Nota3,Promedio) VALUES (?,?,?,?,?,?,?)");
                        p.setNif(txtid.getText());
                        ps.setString(1, p.getNif());
                        p.setNombre(txtnombre.getText());
                        ps.setString(2, p.getNombre());
                        p.setAsignatura(txtasignatura.getText());
                        ps.setString(3, p.getAsignatura());
                        ps.setString(4, "0.00");
                        ps.setString(5, "0.00");
                        ps.setString(6, "0.00");
                        ps.setString(7, "0.00");
                        ps.execute();
                        JOptionPane.showMessageDialog(null, "Alumno añadido al acta");

                        limpiar();

                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Error al añadir Alumno");
                        System.out.println(ex);
                    }

                }

                //   tabla();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Porfavor llene todos los campos");
        }

    }//GEN-LAST:event_JBTguardarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
         PreparedStatement ps = null;
        // txtId.setText("");
        //int Fila = tablausuarios.getSelectedRow();
        String comp = txtid.getText();
        int a=buscar();
        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea eliminar a este alumno del acta?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {
            try {

                Conexion objCon = new Conexion();
                com.mysql.jdbc.Connection conn = objCon.getConexion();
                ps = conn.prepareStatement("DELETE FROM acta WHERE Nif=? AND Asignatura=?");
                ps.setString(1, txtid.getText());
                ps.setString(2, txtasignatura.getText());
                ps.execute();
                if ("...".equals(comp)) {
                    JOptionPane.showMessageDialog(null, "No se ha seleccionado ningun alumno");
                } else {
                    if (a==0) {
                        JOptionPane.showMessageDialog(null, "El Alumno no se encuentra en el acta");
                    }else{
                        JOptionPane.showMessageDialog(null, "Alumno Eliminado del acta");
                    }
                    
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al Eliminar alumno del acta");
                System.out.println(ex.toString());
            }

            
            limpiar();
                    }
    }//GEN-LAST:event_eliminarActionPerformed

    private void cbogrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbogrupoActionPerformed
        for (int i = jtProductos.getRowCount() - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
        /*borrar = jtProductos.getRowCount();
        if (borrar == 1) {

            modelo.removeRow(0);

        } else {
            for (int i = 0; i < jtProductos.getRowCount(); i++) {
                modelo.removeRow(i);
            }
            // modelo.removeRow(0);
                   // modelo.removeRow(0);
        }

      //  borrar = 1*/;
        tabla();

    }//GEN-LAST:event_cbogrupoActionPerformed
    public void tabla() {
        int i = 0;
        //
        try {
            jtProductos.setModel(modelo);
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion conn = new Conexion();
            // Connection conn = objCon.getConexion();
            java.sql.Connection con = conn.getConexion();
//ps = conn.prepareStatement("SELECT codigo, nombre, precio, cantidad FROM producto WHERE codigo=?");

            //rs = ps.executeQuery();
            String sql = "SELECT * FROM matricula WHERE Asignatura = ?";
            ps = con.prepareStatement(sql);
            ps.setString(1, cbogrupo.getSelectedItem().toString());
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            // int cantidadColumnas = rsMd.getColumnCount();

            //modelo.addColumn("Direccion");
            // Object[] fila = new Object[7];
            /* fila[3] = cbochofer.getSelectedItem().toString();
            fila[4] = txtnac.getText();
            fila[5] = txtdisco.getText();
            fila[6] = cboestado.getSelectedItem().toString();
               // modelo.addRow(fila);
             */
            while (rs.next()) {
                Object[] filas = new Object[3];

                filas[0] = rs.getString("Nif");
                filas[1] = rs.getString("Nombre_alu");
                filas[2] = rs.getString("Asignatura");
                i++;
                modelo.addRow(filas);
            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }
    }

    private int buscar() {
        PreparedStatement ps = null;
        ResultSet rs = null;
        int c = 0;
        try {
            Conexion objCon = new Conexion();
            Connection conn = objCon.getConexion();

            int Fila = jtProductos.getSelectedRow();
            //String codigo = jtProductos.getValueAt(Fila, 0).toString();
            //String materia = jtProductos.getValueAt(Fila, 2).toString();
            ps = conn.prepareStatement("SELECT * FROM acta WHERE Nif=? AND Asignatura=?");
            ps.setString(1, txtid.getText());
            ps.setString(2, txtasignatura.getText());
            rs = ps.executeQuery();

            while (rs.next()) {
                c = 1;

            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
        return c;
    }
 private void limpiar() {
        //txtcedula.setText("");
        txtid.setText("...");
        txtnombre.setText("...");
        txtasignatura.setText("...");
        

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmActas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmActas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmActas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmActas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmActas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTguardar;
    private javax.swing.JLabel LBLusuarios;
    private javax.swing.JComboBox<String> cbogrupo;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtProductos;
    private javax.swing.JLabel txtasignatura;
    private javax.swing.JLabel txtid;
    private javax.swing.JLabel txtnombre;
    // End of variables declaration//GEN-END:variables

}
