/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectogestion_calificaciones;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author matgr
 */
public class FrmEstadistica extends javax.swing.JFrame {

    /**
     * Creates new form FrmEstadistica
     */
    public FrmEstadistica() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {

            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion conn = new Conexion();
            java.sql.Connection con = conn.getConexion();

            String sql = "SELECT  Nombre FROM grupos";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            while (rs.next()) {

                for (int i = 0; i < cantidadColumnas; i++) {
                    cbogrupo.addItem("" + rs.getObject(i + 1));
                }

            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LBLusuarios = new javax.swing.JLabel();
        cbogrupo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        LBLusuarios.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        LBLusuarios.setText("    Estadística");

        cbogrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione" }));
        cbogrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbogrupoActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione el acta de una asignatura:");

        btnGenerar.setText("Generar Gráfico");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(cbogrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(LBLusuarios))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(btnGenerar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBLusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbogrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGenerar, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbogrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbogrupoActionPerformed

    }//GEN-LAST:event_cbogrupoActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        int i = 0;
        //
        if (cbogrupo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "No ha seleccionado ningun acta");
        } else {
            try {
                // jtNotas.setModel(modelo);
                int est1 = 0, est2 = 0, est3 = 0, est4 = 0, est5 = 0, est6 = 0, est7 = 0, est8 = 0, est9 = 0, est10 = 0;
                double a;
                PreparedStatement ps = null;
                ResultSet rs = null;
                Conexion conn = new Conexion();
                // Connection conn = objCon.getConexion();
                java.sql.Connection con = conn.getConexion();
//ps = conn.prepareStatement("SELECT codigo, nombre, precio, cantidad FROM producto WHERE codigo=?");

                //rs = ps.executeQuery();
                String sql = "SELECT * FROM acta WHERE Asignatura = ?";
                ps = con.prepareStatement(sql);
                ps.setString(1, cbogrupo.getSelectedItem().toString());
                rs = ps.executeQuery();

                //  ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
                // int cantidadColumnas = rsMd.getColumnCount();
                //modelo.addColumn("Direccion");
                // Object[] fila = new Object[7];
                /* fila[3] = cbochofer.getSelectedItem().toString();
            fila[4] = txtnac.getText();
            fila[5] = txtdisco.getText();
            fila[6] = cboestado.getSelectedItem().toString();
               // modelo.addRow(fila);
                 */
                // String vacio,vacio1 = "",vacio2 = "";
                while (rs.next()) {
                    a = Double.parseDouble(rs.getString("Promedio"));
                    if ((a >= 0.00) && (a <= 0.99)) {
                        est1++;
                    }
                    if ((a >= 1.00) && (a <= 1.99)) {
                        est2++;
                    }
                    if ((a >= 2.00) && (a <= 2.99)) {
                        est3++;
                    }
                    if ((a >= 3.00) && (a <= 3.99)) {
                        est4++;
                    }
                    if ((a >= 4.00) && (a <= 4.99)) {
                        est5++;
                    }
                    if ((a >= 5.00) && (a <= 5.99)) {
                        est6++;
                    }
                    if ((a >= 6.00) && (a <= 6.99)) {
                        est7++;
                    }
                    if ((a >= 7.00) && (a <= 7.99)) {
                        est8++;
                    }
                    if ((a >= 8.00) && (a <= 8.99)) {
                        est9++;
                    }
                    if ((a >= 9.00) && (a <= 10.00)) {
                        est10++;
                    }
                }
                DefaultCategoryDataset categoria = new DefaultCategoryDataset();
                String v1 = "0.00-0.99";
                String v2 = "1.00-1.99";
                String v3 = "2.00-2.99";
                String v4 = "3.00-3.99";
                String v5 = "4.00-4.99";
                String v6 = "5.00-5.99";
                String v7 = "6.00-6.99";
                String v8 = "7.00-7.99";
                String v9 = "8.00-8.99";
                String v10 = "9.00-10.00";
                categoria.setValue(est1, v1, v1);
                categoria.setValue(est2, v2, v2);
                categoria.setValue(est3, v3, v3);
                categoria.setValue(est4, v4, v4);
                categoria.setValue(est5, v5, v5);
                categoria.setValue(est6, v6, v6);
                categoria.setValue(est7, v7, v7);
                categoria.setValue(est8, v8, v8);
                categoria.setValue(est9, v9, v9);
                categoria.setValue(est10, v10, v10);
                JFreeChart f = ChartFactory.createBarChart("Calificaciones", "Rango Calificaciones", "Número de alumnos", categoria, PlotOrientation.VERTICAL, true, false, false);
                ChartFrame frame = new ChartFrame("Distribución Calificaciones", f);
                frame.pack();
                frame.setVisible(true);

            } catch (SQLException ex) {
                System.err.println(ex.toString());
            }
        }

    }//GEN-LAST:event_btnGenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEstadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEstadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEstadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEstadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEstadistica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBLusuarios;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JComboBox<String> cbogrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
