/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectogestion_calificaciones;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matgr
 */
public class FrmImprimir extends javax.swing.JFrame implements Printable{
DefaultTableModel modelo = new DefaultTableModel();
    /**
     * Creates new form FrmImprimir
     */
    public FrmImprimir() {
        initComponents();
        jtNotas.setModel(modelo);
        try {

            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion conn = new Conexion();
            java.sql.Connection con = conn.getConexion();

            String sql = "SELECT  Nombre FROM grupos";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            while (rs.next()) {

                for (int i = 0; i < cantidadColumnas; i++) {
                    cbogrupo.addItem("" + rs.getObject(i + 1));
                }

            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }
        modelo.addColumn("Id");
        modelo.addColumn("Nombre");
        
        modelo.addColumn("Nota 1");
        modelo.addColumn("Nota 2");
        modelo.addColumn("Nota 3");
        modelo.addColumn("Promedio");
        //modelo.addColumn("Promedio");
        int[] anchos = {50, 60, 18, 18, 18, 18};
        for (int j = 0; j < jtNotas.getColumnCount(); j++) {
            jtNotas.getColumnModel().getColumn(j).setPreferredWidth(anchos[j]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCalificaciones = new javax.swing.JPanel();
        LBLusuarios = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbogrupo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtNotas = new javax.swing.JTable();
        PanelNotas = new javax.swing.JPanel();
        btnimprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        PanelCalificaciones.setBackground(new java.awt.Color(255, 255, 255));

        LBLusuarios.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        LBLusuarios.setText(" CALIFICACIONES");

        jLabel1.setText("Seleccione el acta de la asignatura:");

        cbogrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione" }));
        cbogrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbogrupoActionPerformed(evt);
            }
        });

        jtNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Asignatura"
            }
        ));
        jtNotas.setToolTipText("");
        jtNotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtNotasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtNotas);

        javax.swing.GroupLayout PanelCalificacionesLayout = new javax.swing.GroupLayout(PanelCalificaciones);
        PanelCalificaciones.setLayout(PanelCalificacionesLayout);
        PanelCalificacionesLayout.setHorizontalGroup(
            PanelCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCalificacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCalificacionesLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(96, 96, 96)
                        .addComponent(cbogrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCalificacionesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LBLusuarios)
                        .addGap(196, 196, 196))))
            .addGroup(PanelCalificacionesLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 80, Short.MAX_VALUE))
        );
        PanelCalificacionesLayout.setVerticalGroup(
            PanelCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCalificacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBLusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(PanelCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbogrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        PanelNotas.setBackground(new java.awt.Color(255, 255, 255));

        btnimprimir.setText("Imprimir");
        btnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelNotasLayout = new javax.swing.GroupLayout(PanelNotas);
        PanelNotas.setLayout(PanelNotasLayout);
        PanelNotasLayout.setHorizontalGroup(
            PanelNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelNotasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        PanelNotasLayout.setVerticalGroup(
            PanelNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNotasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCalificaciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelNotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelCalificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
        try {
            PrinterJob gsp=PrinterJob.getPrinterJob();
            gsp.setPrintable(this);
            boolean top=gsp.printDialog();
            if (top) {
                gsp.print();
            }
        } catch (PrinterException pex) {
            JOptionPane.showMessageDialog(null, "ERROR DE PROGRAMA","Error\n"+pex,JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnimprimirActionPerformed

    private void cbogrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbogrupoActionPerformed
        for (int i = jtNotas.getRowCount() - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
        /*borrar = jtProductos.getRowCount();
        if (borrar == 1) {

            modelo.removeRow(0);

        } else {
            for (int i = 0; i < jtProductos.getRowCount(); i++) {
                modelo.removeRow(i);
            }
            // modelo.removeRow(0);
            // modelo.removeRow(0);
        }

        //  borrar = 1*/;

        tabla();
    }//GEN-LAST:event_cbogrupoActionPerformed

    private void jtNotasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtNotasMouseClicked

       
    }//GEN-LAST:event_jtNotasMouseClicked
public void tabla() {
        int i = 0;
        //
        try {
            jtNotas.setModel(modelo);
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion conn = new Conexion();
            // Connection conn = objCon.getConexion();
            java.sql.Connection con = conn.getConexion();
//ps = conn.prepareStatement("SELECT codigo, nombre, precio, cantidad FROM producto WHERE codigo=?");

            //rs = ps.executeQuery();
            String sql = "SELECT * FROM acta WHERE Asignatura = ?";
            ps = con.prepareStatement(sql);
            ps.setString(1, cbogrupo.getSelectedItem().toString());
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            // int cantidadColumnas = rsMd.getColumnCount();

            //modelo.addColumn("Direccion");
            // Object[] fila = new Object[7];
            /* fila[3] = cbochofer.getSelectedItem().toString();
            fila[4] = txtnac.getText();
            fila[5] = txtdisco.getText();
            fila[6] = cboestado.getSelectedItem().toString();
               // modelo.addRow(fila);
             */
            String vacio,vacio1 = "",vacio2 = "";
            while (rs.next()) {
                Object[] filas = new Object[6];

                filas[0] = rs.getString("Nif");
                filas[1] = rs.getString("Nombre");
                //filas[2] = rs.getString("Asignatura");
                filas[2] = rs.getString("Nota1");
                filas[3] = rs.getString("Nota2");
                filas[4] = rs.getString("Nota3");
                filas[5] = rs.getString("Promedio");
                //filas[6] = rs.getString("Nota1");;
                i++;
                modelo.addRow(filas);
            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmImprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmImprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmImprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmImprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmImprimir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBLusuarios;
    private javax.swing.JPanel PanelCalificaciones;
    private javax.swing.JPanel PanelNotas;
    private javax.swing.JButton btnimprimir;
    private javax.swing.JComboBox<String> cbogrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtNotas;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graf, PageFormat pagfor, int index) throws PrinterException 
    {
        if (index>0) {
            return NO_SUCH_PAGE;
        }
        Graphics2D hub=(Graphics2D) graf;
        hub.translate(pagfor.getImageableX()+30, pagfor.getImageableY()+30);
        hub.scale(1.0, 1.0);
        PanelCalificaciones.printAll(graf);
        return PAGE_EXISTS;
    }
}
