/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectogestion_calificaciones;

import Atxy2k.CustomTextField.RestrictedTextField;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author matgr
 */
public class FrmMatriculacion extends javax.swing.JFrame {

    /**
     * Creates new form FrmMatriculacion
     */
    int cont = 0, cont1 = 0;

    public FrmMatriculacion() {
        initComponents();
        RestrictedTextField l1 = new RestrictedTextField(txtnif);
        l1.setLimit(9);
        txtId1.setVisible(false);
        txtmateria.setVisible(false);
        txtId2.setVisible(false);
        txtname.setVisible(false);
        btnRegresar.setVisible(false);
        //  btnRegresar.setVisible(false);
        try {

            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion conn = new Conexion();
            java.sql.Connection con = conn.getConexion();

            String sql = "SELECT  Nombre FROM grupos";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            while (rs.next()) {

                for (int i = 0; i < cantidadColumnas; i++) {
                    cbomateria.addItem("" + rs.getObject(i + 1));
                }

            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LBLusuarios = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtnif = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbomateria = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lblcreditos = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblhorario = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblalumno = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblcupos1 = new javax.swing.JLabel();
        txtmateria = new javax.swing.JTextField();
        txtId1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtId2 = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        LBLusuarios.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        LBLusuarios.setText("MATRICULACIÓN");

        jLabel1.setText("Seleccione la asignatura a matricularse:");

        txtnif.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnifFocusLost(evt);
            }
        });
        txtnif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnifActionPerformed(evt);
            }
        });
        txtnif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnifKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnifKeyReleased(evt);
            }
        });

        jLabel2.setText("Ingrese el nif del alumno:");

        cbomateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione" }));
        cbomateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbomateriaActionPerformed(evt);
            }
        });

        jLabel3.setText("Numero de Creditos:");

        lblcreditos.setText("...");

        jLabel5.setText("Horario:");

        lblhorario.setText("...");

        jButton1.setText("Registrar Mátricula");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");

        jLabel4.setText("Nombre alumno:");

        lblalumno.setText("...");

        jLabel6.setText("Cupos Disponibles:");

        lblcupos1.setText("...");

        txtmateria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmateriaFocusLost(evt);
            }
        });
        txtmateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmateriaActionPerformed(evt);
            }
        });
        txtmateria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmateriaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmateriaKeyReleased(evt);
            }
        });

        txtId1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtId1FocusLost(evt);
            }
        });
        txtId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId1ActionPerformed(evt);
            }
        });
        txtId1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtId1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtId1KeyReleased(evt);
            }
        });

        txtId2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtId2FocusLost(evt);
            }
        });
        txtId2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId2ActionPerformed(evt);
            }
        });
        txtId2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtId2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtId2KeyReleased(evt);
            }
        });

        txtname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnameFocusLost(evt);
            }
        });
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnameKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblhorario, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnif, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcupos1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblalumno, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txtId1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtmateria, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cbomateria, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jButton1)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtId2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addComponent(btnRegresar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LBLusuarios)
                        .addGap(166, 166, 166))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(LBLusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(11, 11, 11)
                .addComponent(txtmateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblalumno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbomateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhorario, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcupos1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtId2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnifActionPerformed

    }//GEN-LAST:event_txtnifActionPerformed

    private void txtnifKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnifKeyPressed

    }//GEN-LAST:event_txtnifKeyPressed

    private void txtnifKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnifKeyReleased

    }//GEN-LAST:event_txtnifKeyReleased

    private void txtnifFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnifFocusLost
        PreparedStatement ps = null;
        ResultSet rs = null;
        Conexion conn = new Conexion();
        if ((txtId1.getText().equals(""))) {
            iguales();
            nombreAsig();
        }
        try {

            java.sql.Connection con = conn.getConexion();
            ps = con.prepareStatement("SELECT * FROM gestion_alumnos WHERE Nif = ?");
            ps.setString(1, txtnif.getText());

            rs = ps.executeQuery();

            if (rs.next()) {
                lblalumno.setText(rs.getString("Nombre"));

            } else {
                JOptionPane.showMessageDialog(null, "Alumno no encontrado");
                txtnif.setText("");
            }

        } catch (Exception e) {
            System.err.println(e);
        }


    }//GEN-LAST:event_txtnifFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        PreparedStatement ps = null;
        try {
            String comp = txtId1.getText();
            System.out.println(comp);
            int conv = Integer.parseInt(lblcupos1.getText());
            //int Fila = tablausuarios.getSelectedRow();
            String comp1 = "";
            // String comp2 = "...";
            System.out.println(comp);
            if ("".equals(comp)) {
                comp = ".";
            }

            if ((comp1.equals(txtnif.getText())) || (cbomateria.getSelectedIndex() == 0)) {
                JOptionPane.showMessageDialog(null, "Porfavor llene todos los campos");
            } else {
                if (((cbomateria.getSelectedItem().toString()).equals(txtmateria.getText())) || ((txtname.getText()).equals(txtId2.getText()))) {
                    JOptionPane.showMessageDialog(null, "El alumno ya se encuentra matriculado en esta asignatura");
                    limpiar();
                } else {
                    // num = Integer.parseInt(txtcedula.getText());

                    if (conv > 0) {
                        try {
                            Conexion objCon = new Conexion();
                            Connection conn = objCon.getConexion();
                            Matricula p = new Matricula();
                            ps = conn.prepareStatement("INSERT INTO matricula (Nif,Nombre_alu,Asignatura,Numero,Horario,Nombre_A) VALUES (?,?,?,?,?,?)");
                            p.setNif(txtnif.getText());
                            ps.setString(1, p.getNif());
                            p.setAlumnos(lblalumno.getText());
                            ps.setString(2, p.getAlumnos());
                            p.setAsignatura(cbomateria.getSelectedItem().toString());
                            ps.setString(3, p.getAsignatura());
                            p.setNumero(lblcreditos.getText());
                            ps.setString(4, p.getNumero());
                            p.setHorario(lblhorario.getText());
                            ps.setString(5, p.getHorario());
                            ps.setString(6, txtname.getText());
                            cuposdisp();

                            ps.execute();
                            JOptionPane.showMessageDialog(null, "Matricula Registrada");

                            limpiar();

                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(null, "Error al registrar Matricula");
                            System.out.println(ex);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Este grupo ya no esta disponible");
                    }

                }

                //   tabla();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Porfavor llene todos los campos");
        }

    }//GEN-LAST:event_jButton1ActionPerformed
    private void limpiar() {
        lblcreditos.setText("...");
        lblhorario.setText("...");
        lblalumno.setText("...");
        lblcupos1.setText("...");
        cbomateria.setSelectedIndex(0);
        txtnif.setText("");
        txtId1.setText("");
        txtmateria.setText("");
        txtId2.setText("");
        txtname.setText("");
    }
    private void cbomateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbomateriaActionPerformed
        PreparedStatement ps = null;
        ResultSet rs = null;
        Conexion conn = new Conexion();
        String mat;
        iguales();
        if (cbomateria.getSelectedIndex() == 0) {
            txtname.setText("");
            lblcupos1.setText("...");
            lblhorario.setText("...");
            lblcreditos.setText("...");
        } else {
            try {

                java.sql.Connection con = conn.getConexion();
                ps = con.prepareStatement("SELECT * FROM grupos WHERE Nombre = ?");
                ps.setString(1, cbomateria.getSelectedItem().toString());

                rs = ps.executeQuery();

                if (rs.next()) {
                    mat = rs.getString("NombreA");
                    buscarl(mat);
                    txtname.setText(mat);
                    lblcupos1.setText(rs.getString("Cupos_disp"));
                    lblhorario.setText(rs.getString("Horario"));
                    nombreAsig();
                } else {
                    //JOptionPane.showMessageDialog(null, "Asignatura no registrada");
                }

            } catch (Exception e) {
                System.err.println(e);
            }
        }

    }//GEN-LAST:event_cbomateriaActionPerformed
    private void cuposdisp() {
        PreparedStatement ps = null;
        //  int Fila = tablausuarios.getSelectedRow();
        int conv = Integer.parseInt(lblcupos1.getText());
        conv--;

        String cupos = String.valueOf(conv);
        try {
            Conexion objCon = new Conexion();
            com.mysql.jdbc.Connection conn = objCon.getConexion();

            ps = conn.prepareStatement("UPDATE grupos SET Cupos_disp=? WHERE Nombre=?");

            ps.setString(1, cupos);
            ps.setString(2, cbomateria.getSelectedItem().toString());
            ps.execute();
            //JOptionPane.showMessageDialog(null, "Alumno Modificado");

            //  limpiar();
            //   conn.close();
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(null, "Error al Modificar Alumno");
            System.err.println(ex);
        }

        // return cont;
    }

    private void iguales() {
        PreparedStatement ps = null;
        ResultSet rs = null;
        Conexion conn = new Conexion();

        try {

            java.sql.Connection con = conn.getConexion();
            ps = con.prepareStatement("SELECT * FROM matricula WHERE Nif = ? AND Asignatura=?");
            ps.setString(1, txtnif.getText());
            ps.setString(2, cbomateria.getSelectedItem().toString());
            rs = ps.executeQuery();

            if (rs.next()) {

                txtId1.setText(txtnif.getText());
                txtmateria.setText(cbomateria.getSelectedItem().toString());

            } else {
                // JOptionPane.showMessageDialog(null, "Asignatura no registrada");
                cont = 0;
            }

        } catch (Exception e) {
            System.err.println(e);
        }
    }

    private void nombreAsig() {
        PreparedStatement ps = null;
        ResultSet rs = null;
        Conexion conn = new Conexion();

        try {

            java.sql.Connection con = conn.getConexion();
            ps = con.prepareStatement("SELECT * FROM matricula WHERE Nif = ? AND Nombre_A=?");
            ps.setString(1, txtnif.getText());
            ps.setString(2, txtname.getText());
            rs = ps.executeQuery();

            if (rs.next()) {

                //txtId1.setText(txtnif.getText());
                txtId2.setText(txtname.getText());

            } else {
                // JOptionPane.showMessageDialog(null, "Asignatura no registrada");
                cont = 0;
            }

        } catch (Exception e) {
            System.err.println(e);
        }
    }
    private void txtmateriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmateriaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmateriaFocusLost

    private void txtmateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmateriaActionPerformed

    private void txtmateriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmateriaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmateriaKeyPressed

    private void txtmateriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmateriaKeyReleased

    }//GEN-LAST:event_txtmateriaKeyReleased

    private void txtId1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtId1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId1FocusLost

    private void txtId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId1ActionPerformed

    private void txtId1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtId1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId1KeyPressed

    private void txtId1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtId1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId1KeyReleased

    private void txtId2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtId2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId2FocusLost

    private void txtId2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId2ActionPerformed

    private void txtId2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtId2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId2KeyPressed

    private void txtId2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtId2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId2KeyReleased

    private void txtnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameFocusLost

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameKeyPressed

    private void txtnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameKeyReleased
    private void buscarl(String mat) {
        PreparedStatement ps = null;
        ResultSet rs = null;
        Conexion conn = new Conexion();

        try {

            java.sql.Connection con = conn.getConexion();
            ps = con.prepareStatement("SELECT * FROM asignaturas WHERE Nombre = ?");
            ps.setString(1, mat);

            rs = ps.executeQuery();

            if (rs.next()) {
                lblcreditos.setText(rs.getString("Numero"));

            } else {
                //JOptionPane.showMessageDialog(null, "Asignatura no registrada");
            }

        } catch (Exception e) {
            System.err.println(e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMatriculacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMatriculacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMatriculacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMatriculacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMatriculacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBLusuarios;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbomateria;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblalumno;
    private javax.swing.JLabel lblcreditos;
    private javax.swing.JLabel lblcupos1;
    private javax.swing.JLabel lblhorario;
    private javax.swing.JTextField txtId1;
    private javax.swing.JTextField txtId2;
    private javax.swing.JTextField txtmateria;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnif;
    // End of variables declaration//GEN-END:variables
}
